apiVersion: apps/v1
kind: Deployment
metadata:
  name: filter-service-app
spec:
  selector:
    matchLabels:
      app: filter-service-app
  template:
    metadata:
      labels:
        app: filter-service-app
    spec:
      containers:
      - name: filter-service-app
        image: IMAGE_URL/filterservice
        imagePullPolicy: Always
        ports:
        - containerPort: 8083
        env:
        - name: CONFIG_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: config-cm
              key: CONFIG_URL
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-cm
              key: HOSTNAME
        - name: SPRING_PROFILES_ACTIVE
          valueFrom: 
            configMapKeyRef:
              name: common-cm
              key: SPRING_PROFILES_ACTIVE

---

apiVersion: v1
kind: Service
metadata:
  name: filter-service-svc
spec:
  selector:
    app: filter-service-app
  ports:
  - port: 80
    targetPort: 8083
